skip_branch_with_pr: true
version: '{build}'
image: Visual Studio 2017

platform:
  - x64

# cache:
#   - C:\\R\\
#   - C:\\Rtools

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest https://gist.githubusercontent.com/rok-cesnovar/0d74c310d41b12e62f842de4ea92322b/raw/90b718b2dac8dbf0fda49abdf0b6bd29b344be35/appveyor_install_cmdstanr.R -OutFile "..\appveyor_install_cmdstanr.R"
clone_folder: c:\projects\cmdstanr
shallow_clone: true
clone_depth: 1

environment:
  NOT_CRAN: true
  _R_CHECK_FORCE_SUGGESTS_: false
  USE_RTOOLS: true
  HOME: C:\Users\appveyor\

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: |
        if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  
        & "C:\\Program Files\\Git\\mingw64\\bin\\curl.exe" -s -o ../R-win.exe -L https://cran.rstudio.com/bin/windows/base/R-3.6.1-win.exe
        echo "Running R installer"
        Start-Process -FilePath ..\R-win.exe -ArgumentList "/VERYSILENT /DIR=C:\R" -NoNewWindow -Wait
        & "C:\\Program Files\\Git\\mingw64\\bin\\curl.exe" -s -o ../R-tools-win.exe -L https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe
        echo "Running RTools installer"
        Start-Process -FilePath ..\R-tools-win.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
  - SET PATH=C:\\R\\bin\\x64;C:\\Rtools\\bin;C:\\Rtools\\mingw_64\\bin;C:\\Rtools\\mingw_32\\bin;%PATH%
  - g++ --version
  - mingw32-make --version
  - Rscript -e "sessionInfo()"
  - Rscript ..\\appveyor_install_cmdstanr.R 
  - bash inst/make_cmdstan.sh -j2 -w
  - echo "Installation done"

build: false

test_script:
  - SET PATH=C:\\R\\bin\\x64;C:\\Rtools\\bin;C:\\Rtools\\mingw_64\\bin;%PATH%
  - R.exe CMD build . --no-build-vignettes --no-manual
  - R.exe CMD check .\\cmdstanr_0.0.0.9000.tar.gz --no-build-vignettes --no-manual --as-cran --install-args=--build

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits