# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache:
  directories:
    - $HOME/.cmdstanr
  packages: true


warnings_are_errors: true
env:
  - _R_CHECK_FORCE_SUGGESTS_=false

r_github_packages:
  - r-lib/covr

before_install:
  - sudo bash inst/make_cmdstan.sh -j2

after_success:
    - Rscript -e 'covr::codecov()'
