# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel

cache:
  directories:
    - $HOME/.cmdstanr
  packages: true

r_github_packages:
  - r-lib/covr
  - stan-dev/cmdstanr

warnings_are_errors: true
env:
  - NOT_CRAN=true _R_CHECK_FORCE_SUGGESTS_=false

# this before_script works if cmdstanr is in r_github_packages above
before_script:
  - Rscript -e 'cmdstanr::install_cmdstan(cores = 2, overwrite = TRUE)'
  - sudo touch $HOME/.cmdstanr/cmdstan/make/local
  - sudo chown -R $USER:$USER $HOME/.cmdstanr/cmdstan/make/local

after_success:
  - travis_wait Rscript -e 'covr::codecov(line_exclusions = list("R/zzz.R"))'
