# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
addons:
  apt:
    packages:
    - python2.7
    - python3.6

cache: packages
cache:
  directories:
  - $HOME/.cmdstanr

env:
  - _R_CHECK_FORCE_SUGGESTS_=false

install:
  - python inst/install_cmdstan.py -d '~/.cmdstanr'

before_script:
  - export CMDSTAN='~/.cmdstanr/cmdstan'
